# .github/workflows/publish.yml
name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags with semantic versioning

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: python -m pip install build twine
    - run: python -m build
    - run: python -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}